PROGRESS_TEXTS = {
    "expense_saved": "✅ Расход сохранен.\nПрогноз месяца обновлен.",
    "income_saved": "✅ Доход сохранен.\nБаланс месяца пересчитан.",
    "payment_done": "✅ Платеж отмечен как выполненный.\nБлижайшее обязательство — {days_text}.",
    "month_summary_title": "📊 Сейчас по месяцу:",
    "month_summary_income": "Доходы: {income}",
    "month_summary_expense": "Расходы: {expense}",
    "month_summary_balance": "Баланс: {balance}",
    "motivation_operations": "💡 Вы уже внесли {count} операций в этом месяце.",
    "motivation_accuracy": "📌 Чем точнее учет, тем спокойнее финансовый план.",
    "motivation_updated": "✅ Сегодня данные обновлены — лишнее не придется держать в голове.",
    "streak": "🔥 Учет ведется {days} дней подряд.",
    "achievement_first_operation": "✅ Первый шаг сделан — учет начат.",
    "achievement_streak_7": "🎯 Неделя учета без пропусков.",
    "achievement_streak_30": "📈 Полный месяц финансового контроля.",
    "achievement_100_operations": "💼 Уже 100 операций в истории учета.",
    "progress_title": "📌 Финансовый порядок:",
    "progress_streak": "🔥 Серия: {days} дней",
    "progress_month_operations": "✅ Операций за месяц: {count}",
    "progress_next_payment": "📅 Ближайший платеж: {date} — {title} — {amount}",
    "progress_no_month_operations": "Пока нет операций за этот месяц.",
    "progress_no_payments": "Ближайших платежей нет.",
}
